[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ActVibModules"
version = "1.0"
dependencies = [
    "numpy",
    "pandas",
    "pyarrow",
    "scipy"
]

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters